### PR TITLE
Fix metrics + enhance the pom file!

### PR DESCRIPTION
**Pull request by sgdc3**

### CODE REVIEW

**Comment by sgdc3** [comment]
@James137137 Ok it should work! ;)

**Comment by James137137** [comment]
Building now to test

**Comment by James137137** [comment]
Build Failed

`Started by user James Anderson
Building in workspace /var/lib/jenkins/workspace/FactionChat
 > /usr/lib/git-core/git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > /usr/lib/git-core/git config remote.origin.url https://github.com/James137137/FactionChat # timeout=10
Fetching upstream changes from https://github.com/James137137/FactionChat
 > /usr/lib/git-core/git --version # timeout=10
 > /usr/lib/git-core/git -c core.askpass=true fetch --tags --progress https://github.com/James137137/FactionChat +refs/heads/*:refs/remotes/origin/*
 > /usr/lib/git-core/git rev-parse refs/remotes/origin/master^{commit} # timeout=10
 > /usr/lib/git-core/git rev-parse refs/remotes/origin/origin/master^{commit} # timeout=10
Checking out Revision d71ea4c354f45187b8743e628a4544a7020e7275 (refs/remotes/origin/master)
 > /usr/lib/git-core/git config core.sparsecheckout # timeout=10
 > /usr/lib/git-core/git checkout -f d71ea4c354f45187b8743e628a4544a7020e7275
 > /usr/lib/git-core/git rev-list be0b8bda541e665c2b7defb9cbf626e7db7dab3c # timeout=10
Parsing POMs
Discovered a new module nz.co.lolnet.james137137:factionchat FactionChat
Modules changed, recalculating dependency graph
Established TCP socket on 56769
[FactionChat] $ /var/lib/jenkins/tools/hudson.model.JDK/Java_1.8/bin/java -cp /var/lib/jenkins/plugins/maven-plugin/WEB-INF/lib/maven32-agent-1.7.jar:/var/lib/jenkins/tools/hudson.tasks.Maven_MavenInstallation/Maven/boot/plexus-classworlds-2.5.2.jar:/var/lib/jenkins/tools/hudson.tasks.Maven_MavenInstallation/Maven/conf/logging jenkins.maven3.agent.Maven32Main /var/lib/jenkins/tools/hudson.tasks.Maven_MavenInstallation/Maven /var/cache/jenkins/war/WEB-INF/lib/remoting-2.53.2.jar /var/lib/jenkins/plugins/maven-plugin/WEB-INF/lib/maven32-interceptor-1.7.jar /var/lib/jenkins/plugins/maven-plugin/WEB-INF/lib/maven3-interceptor-commons-1.7.jar 56769
<===[JENKINS REMOTING CAPACITY]===>channel started
Executing Maven:  -B -f /var/lib/jenkins/workspace/FactionChat/pom.xml install
[INFO] Scanning for projects...
[HUDSON] Collecting dependencies info
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building FactionChat 1.9.13-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-compiler-plugin/3.5/maven-compiler-plugin-3.5.pom
[INFO] Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-compiler-plugin/3.5/maven-compiler-plugin-3.5.pom (10 KB at 5.5 KB/sec)
[INFO] Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-compiler-plugin/3.5/maven-compiler-plugin-3.5.jar
[INFO] Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-compiler-plugin/3.5/maven-compiler-plugin-3.5.jar (49 KB at 433.2 KB/sec)
[INFO] Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-shade-plugin/2.4.3/maven-shade-plugin-2.4.3.pom
[INFO] Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-shade-plugin/2.4.3/maven-shade-plugin-2.4.3.pom (9 KB at 121.9 KB/sec)
[INFO] Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-shade-plugin/2.4.3/maven-shade-plugin-2.4.3.jar
[INFO] Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-shade-plugin/2.4.3/maven-shade-plugin-2.4.3.jar (102 KB at 1332.1 KB/sec)
[INFO] Downloading: file:///var/lib/jenkins/workspace/FactionChat/repo/net/ess3/EssentialsX/2.0.1-SNAPSHOT/maven-metadata.xml
[INFO] Downloading: https://hub.spigotmc.org/nexus/content/groups/public/net/ess3/EssentialsX/2.0.1-SNAPSHOT/maven-metadata.xml
[INFO] Downloading: http://ci.xephi.fr/plugin/repository/everything/net/ess3/EssentialsX/2.0.1-SNAPSHOT/maven-metadata.xml
[INFO] Downloading: http://ci.frostcast.net/plugin/repository/everything/net/ess3/EssentialsX/2.0.1-SNAPSHOT/maven-metadata.xml
[INFO] Downloading: http://maven.sk89q.com/repo/net/ess3/EssentialsX/2.0.1-SNAPSHOT/maven-metadata.xml
[INFO] Downloading: http://pex-repo.aoeu.xyz/net/ess3/EssentialsX/2.0.1-SNAPSHOT/maven-metadata.xml
[INFO] Downloading: http://ci.drtshock.net/plugin/repository/everything/net/ess3/EssentialsX/2.0.1-SNAPSHOT/maven-metadata.xml
[INFO] Downloaded: http://ci.drtshock.net/plugin/repository/everything/net/ess3/EssentialsX/2.0.1-SNAPSHOT/maven-metadata.xml (614 B at 0.2 KB/sec)
[WARNING] Could not transfer metadata net.ess3:EssentialsX:2.0.1-SNAPSHOT/maven-metadata.xml from/to pex-repo (http://pex-repo.aoeu.xyz): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[WARNING] Failure to transfer net.ess3:EssentialsX:2.0.1-SNAPSHOT/maven-metadata.xml from http://pex-repo.aoeu.xyz was cached in the local repository, resolution will not be reattempted until the update interval of pex-repo has elapsed or updates are forced. Original error: Could not transfer metadata net.ess3:EssentialsX:2.0.1-SNAPSHOT/maven-metadata.xml from/to pex-repo (http://pex-repo.aoeu.xyz): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[INFO] Downloading: file:///var/lib/jenkins/workspace/FactionChat/repo/net/ess3/EssentialsX/2.0.1-SNAPSHOT/EssentialsX-2.0.1-20150602.152244-98.pom
[INFO] Downloading: http://ci.xephi.fr/plugin/repository/everything/net/ess3/EssentialsX/2.0.1-SNAPSHOT/EssentialsX-2.0.1-20150602.152244-98.pom
[INFO] Downloading: https://hub.spigotmc.org/nexus/content/groups/public/net/ess3/EssentialsX/2.0.1-SNAPSHOT/EssentialsX-2.0.1-20150602.152244-98.pom
[INFO] Downloading: http://maven.sk89q.com/repo/net/ess3/EssentialsX/2.0.1-SNAPSHOT/EssentialsX-2.0.1-20150602.152244-98.pom
[INFO] Downloading: http://ci.frostcast.net/plugin/repository/everything/net/ess3/EssentialsX/2.0.1-SNAPSHOT/EssentialsX-2.0.1-20150602.152244-98.pom
[INFO] Downloading: http://pex-repo.aoeu.xyz/net/ess3/EssentialsX/2.0.1-SNAPSHOT/EssentialsX-2.0.1-20150602.152244-98.pom
[INFO] Downloading: http://ci.drtshock.net/plugin/repository/everything/net/ess3/EssentialsX/2.0.1-SNAPSHOT/EssentialsX-2.0.1-20150602.152244-98.pom
[INFO] Downloaded: http://ci.drtshock.net/plugin/repository/everything/net/ess3/EssentialsX/2.0.1-SNAPSHOT/EssentialsX-2.0.1-20150602.152244-98.pom (5 KB at 1.3 KB/sec)
[INFO] Downloading: file:///var/lib/jenkins/workspace/FactionChat/repo/net/ess3/EssentialsParent/2.0.1-SNAPSHOT/maven-metadata.xml
[INFO] Downloading: https://hub.spigotmc.org/nexus/content/groups/public/net/ess3/EssentialsParent/2.0.1-SNAPSHOT/maven-metadata.xml
[INFO] Downloading: http://maven.sk89q.com/repo/net/ess3/EssentialsParent/2.0.1-SNAPSHOT/maven-metadata.xml
[INFO] Downloading: http://ci.xephi.fr/plugin/repository/everything/net/ess3/EssentialsParent/2.0.1-SNAPSHOT/maven-metadata.xml
[INFO] Downloading: http://ci.frostcast.net/plugin/repository/everything/net/ess3/EssentialsParent/2.0.1-SNAPSHOT/maven-metadata.xml
[INFO] Downloading: http://pex-repo.aoeu.xyz/net/ess3/EssentialsParent/2.0.1-SNAPSHOT/maven-metadata.xml
[INFO] Downloading: http://ci.drtshock.net/plugin/repository/everything/net/ess3/EssentialsParent/2.0.1-SNAPSHOT/maven-metadata.xml
[INFO] Downloaded: http://ci.drtshock.net/plugin/repository/everything/net/ess3/EssentialsParent/2.0.1-SNAPSHOT/maven-metadata.xml (445 B at 0.1 KB/sec)
[WARNING] Could not transfer metadata net.ess3:EssentialsParent:2.0.1-SNAPSHOT/maven-metadata.xml from/to pex-repo (http://pex-repo.aoeu.xyz): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[INFO] Downloading: http://ci.drtshock.net/plugin/repository/everything/net/ess3/EssentialsParent/2.0.1-SNAPSHOT/EssentialsParent-2.0.1-20150602.152244-98.pom
[INFO] Downloaded: http://ci.drtshock.net/plugin/repository/everything/net/ess3/EssentialsParent/2.0.1-SNAPSHOT/EssentialsParent-2.0.1-20150602.152244-98.pom (19 KB at 5.5 KB/sec)
[WARNING] The POM for net.ess3:EssentialsX:jar:2.0.1-20150602.152244-98 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[INFO] Downloading: file:///var/lib/jenkins/workspace/FactionChat/repo/net/milkbowl/vault/Vault/1.5.6/Vault-1.5.6.pom
[INFO] Downloading: http://ci.xephi.fr/plugin/repository/everything/net/milkbowl/vault/Vault/1.5.6/Vault-1.5.6.pom
[INFO] Downloading: https://hub.spigotmc.org/nexus/content/groups/public/net/milkbowl/vault/Vault/1.5.6/Vault-1.5.6.pom
[INFO] Downloading: http://maven.sk89q.com/repo/net/milkbowl/vault/Vault/1.5.6/Vault-1.5.6.pom
[INFO] Downloading: http://ci.frostcast.net/plugin/repository/everything/net/milkbowl/vault/Vault/1.5.6/Vault-1.5.6.pom
[INFO] Downloading: http://pex-repo.aoeu.xyz/net/milkbowl/vault/Vault/1.5.6/Vault-1.5.6.pom
[INFO] Downloading: http://ci.drtshock.net/plugin/repository/everything/net/milkbowl/vault/Vault/1.5.6/Vault-1.5.6.pom
[INFO] Downloading: https://repo.maven.apache.org/maven2/net/milkbowl/vault/Vault/1.5.6/Vault-1.5.6.pom
[INFO] Downloading: file:///var/lib/jenkins/workspace/FactionChat/repo/de/bananaco/bPermissions/2.12-DEV/bPermissions-2.12-DEV.pom
[INFO] Downloading: http://ci.xephi.fr/plugin/repository/everything/de/bananaco/bPermissions/2.12-DEV/bPermissions-2.12-DEV.pom
[INFO] Downloaded: http://ci.xephi.fr/plugin/repository/everything/de/bananaco/bPermissions/2.12-DEV/bPermissions-2.12-DEV.pom (0 B at 0.0 KB/sec)
[INFO] Downloading: file:///var/lib/jenkins/workspace/FactionChat/repo/fr/xephi/authme/5.2-SNAPSHOT/maven-metadata.xml
[INFO] Downloading: http://ci.xephi.fr/plugin/repository/everything/fr/xephi/authme/5.2-SNAPSHOT/maven-metadata.xml
[INFO] Downloading: http://maven.sk89q.com/repo/fr/xephi/authme/5.2-SNAPSHOT/maven-metadata.xml
[INFO] Downloading: https://hub.spigotmc.org/nexus/content/groups/public/fr/xephi/authme/5.2-SNAPSHOT/maven-metadata.xml
[INFO] Downloading: http://ci.frostcast.net/plugin/repository/everything/fr/xephi/authme/5.2-SNAPSHOT/maven-metadata.xml
[INFO] Downloading: http://pex-repo.aoeu.xyz/fr/xephi/authme/5.2-SNAPSHOT/maven-metadata.xml
[INFO] Downloading: http://ci.drtshock.net/plugin/repository/everything/fr/xephi/authme/5.2-SNAPSHOT/maven-metadata.xml
[INFO] Downloaded: http://ci.xephi.fr/plugin/repository/everything/fr/xephi/authme/5.2-SNAPSHOT/maven-metadata.xml (823 B at 1.4 KB/sec)
[WARNING] Could not transfer metadata fr.xephi:authme:5.2-SNAPSHOT/maven-metadata.xml from/to pex-repo (http://pex-repo.aoeu.xyz): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[WARNING] Failure to transfer fr.xephi:authme:5.2-SNAPSHOT/maven-metadata.xml from http://pex-repo.aoeu.xyz was cached in the local repository, resolution will not be reattempted until the update interval of pex-repo has elapsed or updates are forced. Original error: Could not transfer metadata fr.xephi:authme:5.2-SNAPSHOT/maven-metadata.xml from/to pex-repo (http://pex-repo.aoeu.xyz): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[INFO] Downloading: file:///var/lib/jenkins/workspace/FactionChat/repo/fr/xephi/authme/5.2-SNAPSHOT/authme-5.2-20160205.232317-720.pom
[INFO] Downloading: http://ci.xephi.fr/plugin/repository/everything/fr/xephi/authme/5.2-SNAPSHOT/authme-5.2-20160205.232317-720.pom
[INFO] Downloaded: http://ci.xephi.fr/plugin/repository/everything/fr/xephi/authme/5.2-SNAPSHOT/authme-5.2-20160205.232317-720.pom (20 KB at 31.2 KB/sec)
[INFO] Downloading: file:///var/lib/jenkins/workspace/FactionChat/repo/nz/co/lolnet/james137137/FactionsAPI/1.0.8/FactionsAPI-1.0.8.pom
[INFO] Downloaded: file:///var/lib/jenkins/workspace/FactionChat/repo/nz/co/lolnet/james137137/FactionsAPI/1.0.8/FactionsAPI-1.0.8.pom (408 B at 36.2 KB/sec)
[INFO] Downloading: file:///var/lib/jenkins/workspace/FactionChat/repo/org/bukkit/bukkit/1.8.8-R0.1-SNAPSHOT/maven-metadata.xml
[INFO] Downloading: http://maven.sk89q.com/repo/org/bukkit/bukkit/1.8.8-R0.1-SNAPSHOT/maven-metadata.xml
[INFO] Downloading: http://ci.xephi.fr/plugin/repository/everything/org/bukkit/bukkit/1.8.8-R0.1-SNAPSHOT/maven-metadata.xml
[INFO] Downloading: http://pex-repo.aoeu.xyz/org/bukkit/bukkit/1.8.8-R0.1-SNAPSHOT/maven-metadata.xml
[INFO] Downloading: http://ci.frostcast.net/plugin/repository/everything/org/bukkit/bukkit/1.8.8-R0.1-SNAPSHOT/maven-metadata.xml
[INFO] Downloading: http://ci.drtshock.net/plugin/repository/everything/org/bukkit/bukkit/1.8.8-R0.1-SNAPSHOT/maven-metadata.xml
[WARNING] Could not transfer metadata org.bukkit:bukkit:1.8.8-R0.1-SNAPSHOT/maven-metadata.xml from/to pex-repo (http://pex-repo.aoeu.xyz): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[WARNING] Failure to transfer org.bukkit:bukkit:1.8.8-R0.1-SNAPSHOT/maven-metadata.xml from http://pex-repo.aoeu.xyz was cached in the local repository, resolution will not be reattempted until the update interval of pex-repo has elapsed or updates are forced. Original error: Could not transfer metadata org.bukkit:bukkit:1.8.8-R0.1-SNAPSHOT/maven-metadata.xml from/to pex-repo (http://pex-repo.aoeu.xyz): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[INFO] Downloading: file:///var/lib/jenkins/workspace/FactionChat/repo/org/anjocaido/groupmanagerx/2.2-SNAPSHOT/maven-metadata.xml
[INFO] Downloading: http://ci.xephi.fr/plugin/repository/everything/org/anjocaido/groupmanagerx/2.2-SNAPSHOT/maven-metadata.xml
[INFO] Downloading: https://hub.spigotmc.org/nexus/content/groups/public/org/anjocaido/groupmanagerx/2.2-SNAPSHOT/maven-metadata.xml
[INFO] Downloading: http://ci.frostcast.net/plugin/repository/everything/org/anjocaido/groupmanagerx/2.2-SNAPSHOT/maven-metadata.xml
[INFO] Downloading: http://maven.sk89q.com/repo/org/anjocaido/groupmanagerx/2.2-SNAPSHOT/maven-metadata.xml
[INFO] Downloading: http://pex-repo.aoeu.xyz/org/anjocaido/groupmanagerx/2.2-SNAPSHOT/maven-metadata.xml
[INFO] Downloading: http://ci.drtshock.net/plugin/repository/everything/org/anjocaido/groupmanagerx/2.2-SNAPSHOT/maven-metadata.xml
[INFO] Downloaded: http://ci.xephi.fr/plugin/repository/everything/org/anjocaido/groupmanagerx/2.2-SNAPSHOT/maven-metadata.xml (613 B at 0.9 KB/sec)
[WARNING] Could not transfer metadata org.anjocaido:groupmanagerx:2.2-SNAPSHOT/maven-metadata.xml from/to pex-repo (http://pex-repo.aoeu.xyz): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[WARNING] Failure to transfer org.anjocaido:groupmanagerx:2.2-SNAPSHOT/maven-metadata.xml from http://pex-repo.aoeu.xyz was cached in the local repository, resolution will not be reattempted until the update interval of pex-repo has elapsed or updates are forced. Original error: Could not transfer metadata org.anjocaido:groupmanagerx:2.2-SNAPSHOT/maven-metadata.xml from/to pex-repo (http://pex-repo.aoeu.xyz): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[INFO] Downloading: file:///var/lib/jenkins/workspace/FactionChat/repo/org/anjocaido/groupmanagerx/2.2-SNAPSHOT/groupmanagerx-2.2-20160103.150702-2.pom
[INFO] Downloading: http://ci.xephi.fr/plugin/repository/everything/org/anjocaido/groupmanagerx/2.2-SNAPSHOT/groupmanagerx-2.2-20160103.150702-2.pom
[INFO] Downloaded: http://ci.xephi.fr/plugin/repository/everything/org/anjocaido/groupmanagerx/2.2-SNAPSHOT/groupmanagerx-2.2-20160103.150702-2.pom (0 B at 0.0 KB/sec)
[INFO] Downloading: file:///var/lib/jenkins/workspace/FactionChat/repo/ru/tehkode/PermissionsEx/1.23.2-SNAPSHOT/maven-metadata.xml
[INFO] Downloading: http://ci.xephi.fr/plugin/repository/everything/ru/tehkode/PermissionsEx/1.23.2-SNAPSHOT/maven-metadata.xml
[INFO] Downloading: https://hub.spigotmc.org/nexus/content/groups/public/ru/tehkode/PermissionsEx/1.23.2-SNAPSHOT/maven-metadata.xml
[INFO] Downloading: http://maven.sk89q.com/repo/ru/tehkode/PermissionsEx/1.23.2-SNAPSHOT/maven-metadata.xml
[INFO] Downloading: http://ci.frostcast.net/plugin/repository/everything/ru/tehkode/PermissionsEx/1.23.2-SNAPSHOT/maven-metadata.xml
[INFO] Downloading: http://pex-repo.aoeu.xyz/ru/tehkode/PermissionsEx/1.23.2-SNAPSHOT/maven-metadata.xml
[INFO] Downloading: http://ci.drtshock.net/plugin/repository/everything/ru/tehkode/PermissionsEx/1.23.2-SNAPSHOT/maven-metadata.xml
[WARNING] Could not transfer metadata ru.tehkode:PermissionsEx:1.23.2-SNAPSHOT/maven-metadata.xml from/to pex-repo (http://pex-repo.aoeu.xyz): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[WARNING] Failure to transfer ru.tehkode:PermissionsEx:1.23.2-SNAPSHOT/maven-metadata.xml from http://pex-repo.aoeu.xyz was cached in the local repository, resolution will not be reattempted until the update interval of pex-repo has elapsed or updates are forced. Original error: Could not transfer metadata ru.tehkode:PermissionsEx:1.23.2-SNAPSHOT/maven-metadata.xml from/to pex-repo (http://pex-repo.aoeu.xyz): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[INFO] Downloading: file:///var/lib/jenkins/workspace/FactionChat/repo/ru/tehkode/PermissionsEx/1.23.2-SNAPSHOT/PermissionsEx-1.23.2-SNAPSHOT.pom
[INFO] Downloading: http://ci.xephi.fr/plugin/repository/everything/ru/tehkode/PermissionsEx/1.23.2-SNAPSHOT/PermissionsEx-1.23.2-SNAPSHOT.pom
[INFO] Downloading: https://hub.spigotmc.org/nexus/content/groups/public/ru/tehkode/PermissionsEx/1.23.2-SNAPSHOT/PermissionsEx-1.23.2-SNAPSHOT.pom
[INFO] Downloading: http://maven.sk89q.com/repo/ru/tehkode/PermissionsEx/1.23.2-SNAPSHOT/PermissionsEx-1.23.2-SNAPSHOT.pom
[INFO] Downloading: http://ci.frostcast.net/plugin/repository/everything/ru/tehkode/PermissionsEx/1.23.2-SNAPSHOT/PermissionsEx-1.23.2-SNAPSHOT.pom
[INFO] Downloading: http://pex-repo.aoeu.xyz/ru/tehkode/PermissionsEx/1.23.2-SNAPSHOT/PermissionsEx-1.23.2-SNAPSHOT.pom
[INFO] Downloading: http://ci.drtshock.net/plugin/repository/everything/ru/tehkode/PermissionsEx/1.23.2-SNAPSHOT/PermissionsEx-1.23.2-SNAPSHOT.pom
[INFO] Downloading: https://hub.spigotmc.org/nexus/content/groups/public/org/mcstats/bukkit/metrics/R8-SNAPSHOT/maven-metadata.xml
[INFO] Downloading: http://maven.sk89q.com/repo/org/mcstats/bukkit/metrics/R8-SNAPSHOT/maven-metadata.xml
[INFO] Downloading: http://ci.xephi.fr/plugin/repository/everything/org/mcstats/bukkit/metrics/R8-SNAPSHOT/maven-metadata.xml
[INFO] Downloading: file:///var/lib/jenkins/workspace/FactionChat/repo/org/mcstats/bukkit/metrics/R8-SNAPSHOT/maven-metadata.xml
[INFO] Downloading: http://ci.frostcast.net/plugin/repository/everything/org/mcstats/bukkit/metrics/R8-SNAPSHOT/maven-metadata.xml
[INFO] Downloading: http://pex-repo.aoeu.xyz/org/mcstats/bukkit/metrics/R8-SNAPSHOT/maven-metadata.xml
[INFO] Downloading: http://ci.drtshock.net/plugin/repository/everything/org/mcstats/bukkit/metrics/R8-SNAPSHOT/maven-metadata.xml
[INFO] Downloaded: http://ci.xephi.fr/plugin/repository/everything/org/mcstats/bukkit/metrics/R8-SNAPSHOT/maven-metadata.xml (611 B at 1.2 KB/sec)
[WARNING] Could not transfer metadata org.mcstats.bukkit:metrics:R8-SNAPSHOT/maven-metadata.xml from/to pex-repo (http://pex-repo.aoeu.xyz): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[WARNING] Failure to transfer org.mcstats.bukkit:metrics:R8-SNAPSHOT/maven-metadata.xml from http://pex-repo.aoeu.xyz was cached in the local repository, resolution will not be reattempted until the update interval of pex-repo has elapsed or updates are forced. Original error: Could not transfer metadata org.mcstats.bukkit:metrics:R8-SNAPSHOT/maven-metadata.xml from/to pex-repo (http://pex-repo.aoeu.xyz): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[INFO] Downloading: file:///var/lib/jenkins/workspace/FactionChat/repo/org/mcstats/bukkit/metrics/R8-SNAPSHOT/metrics-R8-20160103.150639-17.pom
[INFO] Downloading: http://ci.xephi.fr/plugin/repository/everything/org/mcstats/bukkit/metrics/R8-SNAPSHOT/metrics-R8-20160103.150639-17.pom
[INFO] Downloaded: http://ci.xephi.fr/plugin/repository/everything/org/mcstats/bukkit/metrics/R8-SNAPSHOT/metrics-R8-20160103.150639-17.pom (0 B at 0.0 KB/sec)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 48.537 s
[INFO] Finished at: 2016-02-06T18:13:14+13:00
[INFO] Final Memory: 12M/138M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project factionchat: Could not resolve dependencies for project nz.co.lolnet.james137137:factionchat:jar:1.9.13-SNAPSHOT: Failed to collect dependencies at net.milkbowl.vault:Vault:jar:1.5.6: Failed to read artifact descriptor for net.milkbowl.vault:Vault:jar:1.5.6: Could not transfer artifact net.milkbowl.vault:Vault:pom:1.5.6 from/to pex-repo (http://pex-repo.aoeu.xyz): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[JENKINS] Archiving /var/lib/jenkins/workspace/FactionChat/pom.xml to nz.co.lolnet.james137137/factionchat/1.9.13-SNAPSHOT/factionchat-1.9.13-SNAPSHOT.pom
channel stopped
Archiving artifacts
Finished: FAILURE`

**Comment by sgdc3** [comment]
Vault can't e downloaded... :/ let me check

**Comment by sgdc3** [comment]
Ok, thanks for the fix @James137137 I was at school when i sent the pr, i was unable to double check everything ;)

**Comment by James137137** [comment]
@sgdc3 https://gist.github.com/James137137/1ef68721ce9285d4fdcc

sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

Any ideas?

**Comment by sgdc3** [comment]
Wtf? Let me retry the build...

**Comment by sgdc3** [comment]
http://ci.xephi.fr/job/FactionChat/21/console it works!

**Comment by James137137** [comment]
I'm betting its something to do with the Let's Encrypt certificate (on https://pex-repo.aoeu.xyz/)

**Comment by James137137** [comment]
http://stackoverflow.com/questions/34110426/does-java-support-lets-encrypt-certificates.

Time to work out how to add it :D

**Comment by James137137** [comment]
updating Java first just incase

**Comment by James137137** [comment]
added Cert to ../jre/lib/security/cacerts

Worked fine now

**Comment by sgdc3** [comment]
Fine ;)

**Pull request merged**
